package vista;

import controlador.NotaController;

/**
 *
 * @author mond
 */
public class CMNota extends javax.swing.JPanel {
    /**
     * Creates new form CMNota
     */
     
        
        
    private NotaController notaController = new NotaController();
    String id=null;
    public CMNota() {
        initComponents();
    }
    public CMNota(String titulo,String Contenido,String id){
        txt_titulo.setText(titulo);
        txt_contenido.setText(Contenido);
        this.id=id;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txt_contenido = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_titulo = new javax.swing.JTextField();
        jToolBar1 = new javax.swing.JToolBar();
        btn_guardarNota = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btn_Limpiar_Campos = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        txt_contenido.setColumns(20);
        txt_contenido.setRows(5);
        jScrollPane1.setViewportView(txt_contenido);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabel1.setText("Nota:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jToolBar1.setRollover(true);

        btn_guardarNota.setText("Guardar");
        btn_guardarNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarNotaActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_guardarNota);

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_cancelar);
        jToolBar1.add(jSeparator1);

        btn_Limpiar_Campos.setText("Limpiar Todo");
        btn_Limpiar_Campos.setFocusable(false);
        btn_Limpiar_Campos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Limpiar_Campos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_Limpiar_Campos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Limpiar_CamposActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_Limpiar_Campos);

        btn_eliminar.setText("Eliminar");
        btn_eliminar.setFocusable(false);
        btn_eliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_eliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_eliminar);

        add(jToolBar1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    public String getTitulo() {
        return txt_titulo.getText();
    }

    public String getContenido() {
        return txt_contenido.getText();
    }


    private void limpiarCampos() {
        txt_titulo.setText("");
        txt_contenido.setText("");
    }
    
    private void btn_guardarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarNotaActionPerformed
        if(id==null){
        notaController.crearNota(txt_titulo.getText(), txt_contenido.getText());
        }else if(id!=null){
            notaController.actualizarNota(id, txt_titulo.getText(), txt_contenido.getText());
        }
    }//GEN-LAST:event_btn_guardarNotaActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // cancela la creacion de la nota o la modificacion de la misma y cierra el panel
        // Puedes realizar acciones adicionales antes de cerrar, si es necesario
        // Por ejemplo, limpiar los campos
        limpiarCampos();
        
        // Cierra el panel
        getParent().remove(this);
        revalidate();
        repaint();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_Limpiar_CamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Limpiar_CamposActionPerformed
        limpiarCampos();//limpia campos de la nota
    }//GEN-LAST:event_btn_Limpiar_CamposActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        notaController.eliminarNota(id);
    }//GEN-LAST:event_btn_eliminarActionPerformed
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Limpiar_Campos;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_guardarNota;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextArea txt_contenido;
    private javax.swing.JTextField txt_titulo;
    // End of variables declaration//GEN-END:variables
}
